### ISSUE TITLE
Error running resample_to_csv

### ISSUE THREAD

**Issue by chownc** [chenlocus/pyalgotrade-python-3#1]
Using Python 3.6.2

When following the Bitcoin Charts example 
 http://gbeced.github.io/pyalgotrade/docs/v0.18/html/bitcoincharts_example.html

Got an error message:-
> TypeError: 'dict_keys' object does not support indexing

My fix was to modify pyalgotrade/feed/__init__.py

**Update line 112 from:**
```
    def getKeys(self):
        return self.__ds.keys()
```

**To:**
```
    def getKeys(self):
        return list(self.__ds.keys())
```

**Comment by chenlocus** [comment]
thanks, chownc, I will update with this.
