### ISSUE TITLE
Can't install with pip

### ISSUE THREAD

**Issue by jachymb** [chenlocus/pyalgotrade-python-3#4]
$ pip install pyalgotrade-python-3
    Collecting pyalgotrade-python-3
      Could not find a version that satisfies the requirement pyalgotrade-python-3 (from versions: )
    No matching distribution found for pyalgotrade-python-3

**Comment by chenlocus** [comment]
Please do this to use this module:

pip install pyalgotrade

clone or download this pyalgotrade-python-3, copy all the files and folds under pyalgotrade-python-3 to override existing pyalgotrade.

I have updated in the readme as well.
